# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Eventcal' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Eventcal
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  
  # Pods for Facebook login
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  
  # Pods for calendar
  pod 'JTAppleCalendar', '~> 7.0'
  
end
